# -*- coding: utf-8 -*-
"""End-to-End ML Pipeline with Scikit-learn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/107ZWACm977njdSC0ptpCDXTzWsByLN22

# Task 2: End-to-End ML Pipeline with Scikit-learn
### DevelopersHub Corporation – AI/ML Engineering Internship
**Objective:** Build a reusable, production-ready ML pipeline for predicting customer churn using the Telco Churn Dataset.

Install Dependencies
"""

!pip install scikit-learn pandas numpy matplotlib seaborn joblib -q

"""Import Libraries"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import warnings
warnings.filterwarnings("ignore")

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.metrics import (
    accuracy_score, f1_score, classification_report,
    confusion_matrix, roc_auc_score, roc_curve
)

print("✅ All libraries imported successfully")

"""Load Dataset"""

# Load Telco Churn dataset directly from URL (no login needed)
url = "https://raw.githubusercontent.com/IBM/telco-customer-churn-on-icp4d/master/data/Telco-Customer-Churn.csv"

df = pd.read_csv(url)

print(f"Dataset Shape: {df.shape}")
print(f"\nFirst 5 rows:")
df.head()

"""Exploratory Data Analysis"""

print("=== DATASET INFO ===")
print(df.info())

print("\n=== MISSING VALUES ===")
print(df.isnull().sum()[df.isnull().sum() > 0])

print("\n=== TARGET DISTRIBUTION ===")
print(df['Churn'].value_counts())
print(f"\nChurn Rate: {df['Churn'].value_counts(normalize=True)['Yes']*100:.2f}%")

# Plot churn distribution
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

# Churn count
df['Churn'].value_counts().plot(kind='bar', ax=axes[0],
                                 color=['#2196F3', '#E91E63'],
                                 edgecolor='black')
axes[0].set_title('Churn Distribution', fontweight='bold')
axes[0].set_xlabel('Churn')
axes[0].set_ylabel('Count')
axes[0].tick_params(rotation=0)

# Churn by contract type
pd.crosstab(df['Contract'], df['Churn']).plot(kind='bar', ax=axes[1],
                                               color=['#2196F3', '#E91E63'],
                                               edgecolor='black')
axes[1].set_title('Churn by Contract Type', fontweight='bold')
axes[1].set_xlabel('Contract Type')
axes[1].tick_params(rotation=15)

plt.tight_layout()
plt.savefig('eda_plots.png', dpi=150)
plt.show()

"""Data Preprocessing"""

# Drop customerID (not useful)
df = df.drop(columns=['customerID'])

# Fix TotalCharges — it has spaces, convert to numeric
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

# Fill missing TotalCharges with median
df['TotalCharges'].fillna(df['TotalCharges'].median(), inplace=True)

# Encode target variable
df['Churn'] = (df['Churn'] == 'Yes').astype(int)

print(f"Target encoded: No=0, Yes=1")
print(f"Churn counts:\n{df['Churn'].value_counts()}")

# Separate features and target
X = df.drop(columns=['Churn'])
y = df['Churn']

# Identify column types
categorical_cols = X.select_dtypes(include=['object']).columns.tolist()
numerical_cols   = X.select_dtypes(include=['number']).columns.tolist()

print(f"\nNumerical columns  ({len(numerical_cols)}): {numerical_cols}")
print(f"Categorical columns({len(categorical_cols)}): {categorical_cols}")

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"\nTrain size: {X_train.shape[0]}")
print(f"Test size:  {X_test.shape[0]}")

"""Build Preprocessing + Pipeline"""

# Preprocessing for numerical and categorical features
numerical_transformer = StandardScaler()

categorical_transformer = OneHotEncoder(
    handle_unknown='ignore',
    drop='first'        # avoid multicollinearity
)

# Combine both transformers using ColumnTransformer
preprocessor = ColumnTransformer(transformers=[
    ('num', numerical_transformer, numerical_cols),
    ('cat', categorical_transformer, categorical_cols)
])

# ── Pipeline 1: Logistic Regression ──
lr_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(
        random_state=42,
        max_iter=1000,
        solver='lbfgs'
    ))
])

# ── Pipeline 2: Random Forest ──
rf_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(
        random_state=42,
        n_jobs=-1
    ))
])

print("✅ Pipelines created successfully")
print(f"\nLogistic Regression Pipeline:\n{lr_pipeline}")

"""Train Both Models"""

print("Training Logistic Regression...")
lr_pipeline.fit(X_train, y_train)
lr_preds = lr_pipeline.predict(X_test)
lr_proba = lr_pipeline.predict_proba(X_test)[:, 1]

print("Training Random Forest...")
rf_pipeline.fit(X_train, y_train)
rf_preds = rf_pipeline.predict(X_test)
rf_proba = rf_pipeline.predict_proba(X_test)[:, 1]

print("\n✅ Both models trained successfully!")

# Quick comparison
print("\n=== QUICK RESULTS ===")
print(f"Logistic Regression — Accuracy: {accuracy_score(y_test, lr_preds)*100:.2f}%  |  F1: {f1_score(y_test, lr_preds):.4f}")
print(f"Random Forest       — Accuracy: {accuracy_score(y_test, rf_preds)*100:.2f}%  |  F1: {f1_score(y_test, rf_preds):.4f}")

"""Hyperparameter Tuning with GridSearchCV"""

print("Running GridSearchCV for Logistic Regression...")

lr_param_grid = {
    'classifier__C': [0.01, 0.1, 1, 10],
    'classifier__penalty': ['l2'],
    'classifier__solver': ['lbfgs', 'saga']
}

lr_grid = GridSearchCV(
    lr_pipeline,
    lr_param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)
lr_grid.fit(X_train, y_train)

print(f"\n✅ Best LR Params : {lr_grid.best_params_}")
print(f"   Best LR F1 (CV): {lr_grid.best_score_:.4f}")

# ── GridSearch for Random Forest ──
print("\nRunning GridSearchCV for Random Forest...")

rf_param_grid = {
    'classifier__n_estimators': [100, 200],
    'classifier__max_depth': [None, 10, 20],
    'classifier__min_samples_split': [2, 5]
}

rf_grid = GridSearchCV(
    rf_pipeline,
    rf_param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)
rf_grid.fit(X_train, y_train)

print(f"\n✅ Best RF Params : {rf_grid.best_params_}")
print(f"   Best RF F1 (CV): {rf_grid.best_score_:.4f}")

"""Evaluate Tuned Models"""

# Predictions from best models
best_lr_preds = lr_grid.best_estimator_.predict(X_test)
best_rf_preds = rf_grid.best_estimator_.predict(X_test)
best_lr_proba = lr_grid.best_estimator_.predict_proba(X_test)[:, 1]
best_rf_proba = rf_grid.best_estimator_.predict_proba(X_test)[:, 1]

print("=" * 60)
print("LOGISTIC REGRESSION — Classification Report")
print("=" * 60)
print(classification_report(y_test, best_lr_preds, target_names=['No Churn', 'Churn']))

print("=" * 60)
print("RANDOM FOREST — Classification Report")
print("=" * 60)
print(classification_report(y_test, best_rf_preds, target_names=['No Churn', 'Churn']))

# Summary table
results_df = pd.DataFrame({
    'Model': ['Logistic Regression', 'Random Forest'],
    'Accuracy': [
        accuracy_score(y_test, best_lr_preds),
        accuracy_score(y_test, best_rf_preds)
    ],
    'F1 Score': [
        f1_score(y_test, best_lr_preds),
        f1_score(y_test, best_rf_preds)
    ],
    'ROC-AUC': [
        roc_auc_score(y_test, best_lr_proba),
        roc_auc_score(y_test, best_rf_proba)
    ]
})
results_df = results_df.round(4)
print("\n=== MODEL COMPARISON TABLE ===")
print(results_df.to_string(index=False))

"""Visualizations"""

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# ── 1. Confusion Matrices ──
for ax, preds, title in zip(
    axes[:2],
    [best_lr_preds, best_rf_preds],
    ['Logistic Regression', 'Random Forest']
):
    cm = confusion_matrix(y_test, preds)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax,
                xticklabels=['No Churn', 'Churn'],
                yticklabels=['No Churn', 'Churn'])
    ax.set_title(f'Confusion Matrix\n{title}', fontweight='bold')
    ax.set_ylabel('True Label')
    ax.set_xlabel('Predicted Label')

# ── 2. ROC Curves ──
for proba, label, color in zip(
    [best_lr_proba, best_rf_proba],
    ['Logistic Regression', 'Random Forest'],
    ['#2196F3', '#E91E63']
):
    fpr, tpr, _ = roc_curve(y_test, proba)
    auc = roc_auc_score(y_test, proba)
    axes[2].plot(fpr, tpr, label=f'{label} (AUC={auc:.3f})', color=color, linewidth=2)

axes[2].plot([0,1], [0,1], 'k--', linewidth=1)
axes[2].set_title('ROC Curves', fontweight='bold')
axes[2].set_xlabel('False Positive Rate')
axes[2].set_ylabel('True Positive Rate')
axes[2].legend()
axes[2].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('model_evaluation.png', dpi=150)
plt.show()

"""Feature Importance (Random Forest)"""

# Get feature names after OneHotEncoding
ohe_feature_names = lr_grid.best_estimator_\
    .named_steps['preprocessor']\
    .named_transformers_['cat']\
    .get_feature_names_out(categorical_cols).tolist()

all_feature_names = numerical_cols + ohe_feature_names

# Get RF feature importances
importances = rf_grid.best_estimator_\
    .named_steps['classifier'].feature_importances_

feat_df = pd.DataFrame({
    'Feature': all_feature_names,
    'Importance': importances
}).sort_values('Importance', ascending=False).head(15)

plt.figure(figsize=(10, 6))
sns.barplot(data=feat_df, x='Importance', y='Feature',
            palette='Blues_r', edgecolor='black')
plt.title('Top 15 Feature Importances — Random Forest', fontweight='bold')
plt.xlabel('Importance Score')
plt.tight_layout()
plt.savefig('feature_importance.png', dpi=150)
plt.show()

"""Export Pipeline with joblib"""

# Determine best model
best_model_name = results_df.loc[results_df['F1 Score'].idxmax(), 'Model']
best_pipeline   = lr_grid.best_estimator_ if best_model_name == 'Logistic Regression' \
                  else rf_grid.best_estimator_

print(f"🏆 Best Model: {best_model_name}")

# Export both pipelines
joblib.dump(lr_grid.best_estimator_, 'lr_churn_pipeline.pkl')
joblib.dump(rf_grid.best_estimator_, 'rf_churn_pipeline.pkl')
joblib.dump(best_pipeline,           'best_churn_pipeline.pkl')

print("\n✅ Pipelines exported:")
print("   → lr_churn_pipeline.pkl")
print("   → rf_churn_pipeline.pkl")
print("   → best_churn_pipeline.pkl  (best model)")

# ── Verify by reloading ──
loaded_pipeline = joblib.load('best_churn_pipeline.pkl')
test_preds = loaded_pipeline.predict(X_test)
print(f"\n✅ Reload verification — Accuracy: {accuracy_score(y_test, test_preds)*100:.2f}%")

"""Predict on New Customer (Real-world Usage)"""

# Simulate a new customer record
new_customer = pd.DataFrame([{
    'gender': 'Female',
    'SeniorCitizen': 0,
    'Partner': 'Yes',
    'Dependents': 'No',
    'tenure': 12,
    'PhoneService': 'Yes',
    'MultipleLines': 'No',
    'InternetService': 'Fiber optic',
    'OnlineSecurity': 'No',
    'OnlineBackup': 'No',
    'DeviceProtection': 'No',
    'TechSupport': 'No',
    'StreamingTV': 'Yes',
    'StreamingMovies': 'Yes',
    'Contract': 'Month-to-month',
    'PaperlessBilling': 'Yes',
    'PaymentMethod': 'Electronic check',
    'MonthlyCharges': 85.0,
    'TotalCharges': 1020.0
}])

prediction = loaded_pipeline.predict(new_customer)[0]
probability = loaded_pipeline.predict_proba(new_customer)[0][1]

print("=== NEW CUSTOMER CHURN PREDICTION ===")
print(f"Churn Prediction : {'⚠️  YES — Will Churn' if prediction == 1 else '✅  NO — Will Stay'}")
print(f"Churn Probability: {probability*100:.2f}%")

"""## ✅ Task 2 Summary

| Item | Detail |
|------|--------|
| Dataset | Telco Customer Churn (IBM) |
| Models | Logistic Regression + Random Forest |
| Pipeline Tool | scikit-learn Pipeline + ColumnTransformer |
| Tuning | GridSearchCV (5-fold CV) |
| Export | joblib (.pkl files) |
| Best Metric | ROC-AUC + F1 Score |

**Key Observations:**
- Random Forest generally outperforms Logistic Regression on F1 and AUC
- Month-to-month contract customers have highest churn risk
- tenure and MonthlyCharges are top predictors of churn
- Pipeline ensures preprocessing is never leaked between train/test splits
- Exported .pkl file can be loaded in any Python environment for predictions
"""